### ISSUE TITLE
ValueError: generator already executing

### ISSUE THREAD

**Issue by sakares** [brucechou1983/CheXNet-Keras#19]
I have received the following error message when it finished the second epoch of command `python train.py`

```
6515/6516 [============================>.] - ETA: 0s - loss: 0.7473 - Atelectasis_loss: 0.1070 - Cardiomegaly_loss: 0.0215 - Effusion_loss: 0.0999 - Infiltration_loss: 0.1867 - Mass_loss: 0.0552 - Nodule_loss: 0.0686 - Pneumonia_loss: 0.0160 - Pneumothorax_loss: 0.0484 - Consolidation_loss: 0.0452 - Edema_loss: 0.0185 - Emphysema_loss: 0.0246 - Fibrosis_loss: 0.0183 - Pleural_Thickening_loss: 0.0354 - Hernia_loss: 0.0021

*********************************
current learning rate: 0.0010000000474974513
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main()
  File "train.py", line 215, in main
    class_weight=class_weights,
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2213, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 76, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/paperspace/CheXNet-Keras/callback.py", line 76, in on_epoch_end
    x, y = load_generator_data(self.generator, self.steps, len(self.class_names))
  File "/home/paperspace/CheXNet-Keras/callback.py", line 22, in load_generator_data
    batch_x, batch_y = next(generator)
ValueError: generator already executing
```

My workaround solution is saving `weights.h5` and `best_weights.h5` after each completed epoch during training. So, I can observe the increasing number of the mean auroc after epochs.

Let me guess, Is it something wrong with the `callback.py` file about thread safe?

Note: my machine is [Quadro P6000 Cloud 24GB GPU on Paperspace](https://www.paperspace.com/pricing)

**Comment by sriniwaas** [comment]
I am also getting the exact same error , as above. I am using 1 GPU NVIDIA GE Force 1080Ti. 
Can you please help on how to resolve this ?

**Comment by sakares** [comment]
@sriniwaas my workaround solution was using some bash script to keep running `python train.py` with `epochs=1` and `use_trained_model_weights=true` for resuming a previously trained weight in `config.ini` for 20 times. 

This is my following mean AUC over times of my working around:
```
(epoch#1) auroc: 0.6216547169658407, lr: 0.0010000000474974513
(epoch#1) auroc: 0.6624539839895851, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7223511985902275, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7245217781045141, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7319376427001315, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7337521699849292, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7415622263301795, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7717222500074268, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7599201996609212, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7740021957241613, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7662403674021128, lr: 0.0010000000474974513
(epoch#1) auroc: 0.781771224428674, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7733085337548695, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7844837615676833, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7872583439024002, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7900109958397001, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7816952223922998, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7782832282288866, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7944851444457808, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7807733874013277, lr: 0.0010000000474974513
(epoch#1) auroc: 0.7881068283844926, lr: 0.0010000000474974513

```

However, the learning rate was not updated from my workaround solution but we can still get a good enough mean AUROC model.

**Comment by brucechou1983** [comment]
Hey guys,

Sorry for the inconvenient caused. I'm actually working on a new version of customized generator which is based on the thread safe `keras.utils.Sequence`. Hopefully I will release it after finishing all tests in this week.

**Comment by srinivas1106** [comment]
Thank you @sakares 
Thank you @brucechou1983

**Comment by aguang1201** [comment]
I geted the same error.I changed the keras version to 2.1.2.It is solved.

**Comment by sriniwaas** [comment]
@aguang1201 Thank you for proposing. I also did similar version downgrading. Like Bruce, said, we can fix this to work with the newer version. For now I am training with your suggestion. Thank you.

**Comment by brucechou1983** [comment]
@sakares @sriniwaas @aguang1201 This is fixed. Please update to 0.3.0.

**Comment by sriniwaas** [comment]
Thank you Bruce, for your quick support.
