### ISSUE TITLE
The problem I met when I try to run train.py

### ISSUE THREAD

**Issue by MagicCola** [brucechou1983/CheXNet-Keras#27]
Hi, Bruce.
I am an junior student from university, I find your code is well commented and really helpful to noob like me. However, when I try to run the train.py in the environment tensorflow==1.2 (beacuse when I have installed version 1.4, it said that cudnn6 was not installed, so I choose version 1.4), I met following error code. Could you help me out? 

`** create image generators **
** set output weights path to: ./experiments/1/weights.h5 **
** check multiple gpu availability **
** multi_gpu_model is used! gpus=2 **
2018-03-08 00:39:02.432635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40 24GB, pci bus id: 0000:02:00.0)
2018-03-08 00:39:02.432689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla M40 24GB, pci bus id: 0000:03:00.0)
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    main()
  File "train.py", line 169, in main
    model_train = multi_gpu_model(model, gpus)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/keras/utils/training_utils.py", line 175, in multi_gpu_model
    outputs = model(inputs)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/keras/engine/topology.py", line 2081, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/keras/engine/topology.py", line 2232, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/keras/layers/normalization.py", line 193, in call
    self.momentum),
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1001, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/tensorflow/python/training/moving_averages.py", line 180, in _zero_debias
    "biased", initializer=biased_initializer, trainable=False)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable conv1/bn/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1001, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/keras/layers/normalization.py", line 193, in call
    self.momentum),
  File "/home/amax/anaconda2/envs/pancj/lib/python3.6/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
`
 @brucechou1983

**Comment by brucechou1983** [comment]
@MagicCola You could try either upgrade your Tensorflow or use only single GPU. Since it's not an issue of this project. I will close this issue.
