### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by billhhh** [brucechou1983/CheXNet-Keras#5]
Thank you so much for sharing your training code!! but I encountered an weired error, after running for 1 or 2 epoch, it occurs

*********************************
current learning rate: 0.0010000000474974513
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main()
  File "train.py", line 215, in main
    class_weight=class_weights,
  File "/workspace/huwang/tools/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/workspace/huwang/tools/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2213, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/workspace/huwang/tools/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 76, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/mnt/StorageArray2_DGX1/huwang/dataset/CXR14/CheXNet-Keras-master-20170124/callback.py", line 76, in on_epoch_end
    x, y = load_generator_data(self.generator, self.steps, len(self.class_names))
  File "/home/mnt/StorageArray2_DGX1/huwang/dataset/CXR14/CheXNet-Keras-master-20170124/callback.py", line 22, in load_generator_data
    batch_x, batch_y = next(generator)
ValueError: generator already executing

I am not that familiared with Keras. May I know how to solve it? Thx again

**Comment by brucechou1983** [comment]
Try setting `use_multiprocessing=True` in fit_generator(). Let me know if that doesn't work for you.

**Comment by billhhh** [comment]
It's working, thx, Bruce!!

**Comment by brucechou1983** [comment]
GTK!
